# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  Calcula um intervalo de confiança Bootstrap para diferença de médias
#'
#' @description Utilizando dois vetores \code{numeric} calcula-se o intervalo de
#' Bootstrap de diferença absoluta de médias conforme quantis fornecidos.
#'
#' @param tratamento Um vetor \code{numeric} com o quantidade estudada observada
#' no tratamento
#' @param controle Um vetor \code{numeric} com a quantidade estudada observada
#' no grupo controle
#' @param B_size Um número \code{integer} com o tamanho desejado para a reamostragem
#' Boostrap
#' @param replicas Um número \code{integer} com a quantidade de replicas (simulações)
#' Bootstrap que serão feitas
#' @param inf Um número \code{numeric} informando o quantil inferior do intervalo
#' @param sup Um número \code{numeric} informando o quantil inferior do intervalo
NULL

boot_mean_interval <- function(tratamento, controle, B_size, replicas, inf, sup) {
    .Call('_magikaRp_boot_mean_interval', PACKAGE = 'magikaRp', tratamento, controle, B_size, replicas, inf, sup)
}

#' @title  Calcula um intervalo de confiança Bootstrap para diferença relativa de médias
#'
#' @description Utilizando dois vetores \code{numeric} calcula-se o intervalo de
#' Bootstrap de diferença relativa \eqn{ \frac{mean(tratamento)}{mean(controle)}} de médias, conforme quantis fornecidos.
#'
#' @param tratamento Um vetor \code{numeric} com o quantidade estudada observada
#' no tratamento
#' @param controle Um vetor \code{numeric} com a quantidade estudada observada
#' no grupo controle
#' @param B_size Um número \code{integer} com o tamanho desejado para a reamostragem
#' Boostrap
#' @param replicas Um número \code{integer} com a quantidade de replicas (simulações)
#' Bootstrap que serão feitas
#' @param inf Um número \code{numeric} informando o quantil inferior do intervalo
#' @param sup Um número \code{numeric} informando o quantil inferior do intervalo
#'
#' @export
#'
boot_mean_rel_interval <- function(tratamento, controle, B_size, replicas, inf, sup) {
    .Call('_magikaRp_boot_mean_rel_interval', PACKAGE = 'magikaRp', tratamento, controle, B_size, replicas, inf, sup)
}

#' @title  Calcula um intervalo de confiança Bootstrap para diferença relativa de proporções
#'
#' @description Utilizando dois vetores \code{numeric} calcula-se o intervalo de
#' Bootstrap de diferença relativa \eqn{ \frac{mean(tratamento)}{mean(controle)}} das proporções, conforme quantis fornecidos.
#'
#' @param tratamento Um vetor \code{numeric} com o quantidade estudada observada
#' no tratamento
#' @param controle Um vetor \code{numeric} com a quantidade estudada observada
#' no grupo controle
#' @param B_size Um número \code{integer} com o tamanho desejado para a reamostragem
#' Boostrap
#' @param replicas Um número \code{integer} com a quantidade de replicas (simulações)
#' Bootstrap que serão feitas
#' @param inf Um número \code{numeric} informando o quantil inferior do intervalo
#' @param sup Um número \code{numeric} informando o quantil inferior do intervalo
#'
#' @export
#'
boot_prop_interval <- function(tratamento, controle, B_size, replicas, inf, sup) {
    .Call('_magikaRp_boot_prop_interval', PACKAGE = 'magikaRp', tratamento, controle, B_size, replicas, inf, sup)
}

